### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by xxx2974** [yuminsuh/part_bilinear_reid#7]
Hi, when I run the 'train_market1501.sh' file. It always displays the connection timeout.
--2019-01-10 16:23:16--  (尝试次数： 5)  https://www.dropbox.com/s/2ljm35ztj6hllcu/bvlc_googlenet.caffemodel.pth?dl=0
正在连接 www.dropbox.com (www.dropbox.com)|69.63.181.12|:443... 失败：连接超时。
重试中。

How can I solve the issue??

**Comment by yuminsuh** [comment]
Can you access https://www.dropbox.com/s/2ljm35ztj6hllcu/bvlc_googlenet.caffemodel.pth?dl=0?

**Comment by xxx2974** [comment]
Thanks a lot. I can't open the link, it seems to need a proxy. I asked other person to help me. If possible,you can put it in an open link.
