### ISSUE TITLE
Reproduce Performance Discussion

### ISSUE THREAD

**Issue by khw321** [yuminsuh/part_bilinear_reid#8]
Thanks for the nice job.
I run the eval_market1501.sh, and get such result,
![image](https://user-images.githubusercontent.com/24911307/51016371-1fe1e680-15ab-11e9-8d67-299f929ce658.png)

And the train_market1501.sh result is 
![image](https://user-images.githubusercontent.com/24911307/51016509-8c5ce580-15ab-11e9-9acc-b74349693c1e.png)

How can I get the result in your paper?
Thanks.

**Comment by xxx2974** [comment]
@khw321  Hi ，how can you get the pretrained model,I can't open the link "https://www.dropbox.com/s/2ljm35ztj6hllcu/bvlc_googlenet.caffemodel.pth?dl=0" and "https://www.dropbox.com/s/pzb3ow1793yf8dc/pose_iter_440000.caffemodel.pth?dl=0"

**Comment by khw321** [comment]
@xxx2974 You need to use a proxy.

**Comment by yuminsuh** [comment]
Hi, thanks for your interest in our work.
The result of the code is the one without re-ranking. The corresponding numbers reported in the paper are
top-1 / top-5 / top-10
91.7% / 96.9% / 98.1%.
To get the result with re-ranking, I used the [code](https://github.com/zhunzhong07/person-re-ranking) on top of the above result.

The results in the paper are obtained with caffe. To reproduce the exact numbers, please use this [model](https://www.dropbox.com/s/hp5vgzf2cjbn9rg/test.prototxt?dl=0) and [weights](https://www.dropbox.com/s/f9m91h3fnnpdip2/model.caffemodel?dl=0) trained on the market-1501 dataset. It needs [custom caffe](https://github.com/yuminsuh/caffe_retrieval).
